#############################################################################
# Generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#  Oct 18, 2020 05:53:35 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1185x592+-1502+567
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4484 1421
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Weapon Fire Loop Generator"
    vTcl:DefineAlias "$top" "Toplevel" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 263 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 461 
    vTcl:DefineAlias "$top.fra45" "FrameSampleProperties" vTcl:WidgetProc "Toplevel" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab99 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Volume 
    vTcl:DefineAlias "$site_3_0.lab99" "LabelVolumeSample" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab100 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {max dBFS} 
    vTcl:DefineAlias "$site_3_0.lab100" "LabelMaxVolumeSample" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab101 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text dBFS 
    vTcl:DefineAlias "$site_3_0.lab101" "LabelAVGSample" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab102 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text -12 -textvariable maxVolumeSample 
    vTcl:DefineAlias "$site_3_0.lab102" "SampleMaxVolume" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab103 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text -12 -textvariable avgVolumeSample 
    vTcl:DefineAlias "$site_3_0.lab103" "SampleMaxVolumeAVG" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab105 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Headroom 
    vTcl:DefineAlias "$site_3_0.lab105" "LabelHeadroom" vTcl:WidgetProc "Toplevel" 1
    button $site_3_0.but106 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Play Tail Sample} 
    vTcl:DefineAlias "$site_3_0.but106" "ButtonPlayTailSample" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but106 <ButtonRelease-1> {
        lambda e: playTailSampleButton(e)
    }
    checkbutton $site_3_0.che107 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor nw -background $vTcl(actual_gui_bg) -command update_sample \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable checkSoloSample 
    vTcl:DefineAlias "$site_3_0.che107" "CheckSoloSample" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab108 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Solo 
    vTcl:DefineAlias "$site_3_0.lab108" "LabelSoloSample" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab109 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Tail Fadein MS} 
    vTcl:DefineAlias "$site_3_0.lab109" "LabelTailFadein" vTcl:WidgetProc "Toplevel" 1
    spinbox $site_3_0.spi110 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_sample -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxTailFadein -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi110" "SpinboxTailFadein" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi110 <KeyRelease> {
        lambda e: on_sample_props_changed(e)
    }
    label $site_3_0.lab111 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Tail Offset MS} 
    vTcl:DefineAlias "$site_3_0.lab111" "LabelTailOffset" vTcl:WidgetProc "Toplevel" 1
    spinbox $site_3_0.spi112 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_sample -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxTailOffset -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi112" "SpinboxTailOffset" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi112 <KeyRelease> {
        lambda e: on_sample_props_changed(e)
    }
    spinbox $site_3_0.spi113 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_sample -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxRandCents -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi113" "SpinboxRandOffsetSample" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi113 <KeyRelease> {
        lambda e: on_sample_props_changed(e)
    }
    label $site_3_0.lab114 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Rand Offset Cents} 
    vTcl:DefineAlias "$site_3_0.lab114" "LabelRandOffset" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab115 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Loop Fadeout Start MS} 
    vTcl:DefineAlias "$site_3_0.lab115" "LabelLoopFadeoutStart" vTcl:WidgetProc "Toplevel" 1
    spinbox $site_3_0.spi116 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_sample -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxLoopFadeoutStart \
        -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi116" "SpinboxLoopFadeoutStart" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi116 <KeyRelease> {
        lambda e: on_sample_props_changed(e)
    }
    label $site_3_0.lab117 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Loop Fadeout Length MS} 
    vTcl:DefineAlias "$site_3_0.lab117" "LabelFadeoutLength" vTcl:WidgetProc "Toplevel" 1
    spinbox $site_3_0.spi118 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_sample -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxLoopFadeoutLength \
        -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi118" "SpinboxFadeoutLength" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi118 <KeyRelease> {
        lambda e: on_sample_props_changed(e)
    }
    button $site_3_0.but119 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Play Loop Sample} 
    vTcl:DefineAlias "$site_3_0.but119" "ButtonPlayLoopSample" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but119 <ButtonRelease-1> {
        lambda e: playLoopSampleButton(e)
    }
    label $site_3_0.lab120 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Name 
    vTcl:DefineAlias "$site_3_0.lab120" "LabelCurrentSampleName" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab121 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Sample Name} -textvariable labelCurrentSampleName 
    vTcl:DefineAlias "$site_3_0.lab121" "CurrentSampleName" vTcl:WidgetProc "Toplevel" 1
    entry $site_3_0.ent123 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -invalidcommand on_sample_props_changed \
        -selectbackground blue -selectforeground white \
        -textvariable volumeHeadroomSample -width 54 
    vTcl:DefineAlias "$site_3_0.ent123" "EntryHeadroomSample" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.ent123 <ButtonRelease-1> {
        lambda e: on_sample_props_changed(e)
    }
    bind $site_3_0.ent123 <KeyRelease> {
        lambda e: on_sample_props_changed(e)
    }
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Copy 
    vTcl:DefineAlias "$site_3_0.but46" "ButtonCopy" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but46 <Button-1> {
        lambda e: buttonCopy(e)
    }
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Paste 
    vTcl:DefineAlias "$site_3_0.but47" "ButtonPaste" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but47 <Button-1> {
        lambda e: buttonPaste(e)
    }
    place $site_3_0.lab99 \
        -in $site_3_0 -x 0 -relx 0.656 -y 0 -rely 0.19 -width 0 \
        -relwidth 0.206 -height 0 -relheight 0.08 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab100 \
        -in $site_3_0 -x 0 -relx 0.656 -y 0 -rely 0.266 -width 0 \
        -relwidth 0.136 -height 0 -relheight 0.08 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab101 \
        -in $site_3_0 -x 0 -relx 0.656 -y 0 -rely 0.342 -width 0 \
        -relwidth 0.098 -height 0 -relheight 0.08 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab102 \
        -in $site_3_0 -x 0 -relx 0.81 -y 0 -rely 0.266 -width 0 \
        -relwidth 0.127 -height 0 -relheight 0.08 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab103 \
        -in $site_3_0 -x 0 -relx 0.81 -y 0 -rely 0.342 -width 0 \
        -relwidth 0.127 -height 0 -relheight 0.08 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab105 \
        -in $site_3_0 -x 20 -y 50 -width 63 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but106 \
        -in $site_3_0 -x 300 -y 210 -width 117 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che107 \
        -in $site_3_0 -x 0 -relx 0.361 -y 0 -rely 0.856 -width 0 \
        -relwidth 0.077 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab108 \
        -in $site_3_0 -x 20 -y 220 -width 29 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab109 \
        -in $site_3_0 -x 20 -y 200 -width 81 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi110 \
        -in $site_3_0 -x 170 -y 200 -width 54 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab111 \
        -in $site_3_0 -x 20 -y 170 -width 81 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi112 \
        -in $site_3_0 -x 0 -relx 0.372 -y 0 -rely 0.646 -width 0 \
        -relwidth 0.118 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi113 \
        -in $site_3_0 -x 0 -relx 0.372 -y 0 -rely 0.304 -width 0 \
        -relwidth 0.118 -height 0 -relheight 0.072 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab114 \
        -in $site_3_0 -x 20 -y 80 -width 112 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab115 \
        -in $site_3_0 -x 20 -y 110 -width 130 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi116 \
        -in $site_3_0 -x 170 -y 110 -width 53 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab117 \
        -in $site_3_0 -x 20 -y 140 -width 150 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi118 \
        -in $site_3_0 -x 170 -y 140 -width 53 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but119 \
        -in $site_3_0 -x 300 -y 160 -width 117 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab120 \
        -in $site_3_0 -x 20 -y 20 -width 33 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab121 \
        -in $site_3_0 -x 169 -y 20 -width 252 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent123 \
        -in $site_3_0 -x 0 -relx 0.372 -y 0 -rely 0.19 -width 54 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 0 -relx 0.656 -y 0 -rely 0.456 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.81 -y 0 -rely 0.456 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 263 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 654 
    vTcl:DefineAlias "$top.fra46" "FrameSourceSamples" vTcl:WidgetProc "Toplevel" 1
    set site_3_0 $top.fra46
    listbox $site_3_0.lis47 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Courier New} -size 9} \
        -foreground $vTcl(actual_gui_fg) -height 227 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground blue -selectforeground white -selectmode single \
        -width 507 
    $site_3_0.lis47 configure -font "-family {Courier New} -size 9"
    $site_3_0.lis47 insert end text
    vTcl:DefineAlias "$site_3_0.lis47" "SourceFilesList" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.lis47 <ButtonRelease-1> {
        lambda e: onSelect(e)
    }
    bind $site_3_0.lis47 <FocusOut> {
        lambda e: on_sample_props_changed(e)
    }
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Open Files} 
    vTcl:DefineAlias "$site_3_0.but50" "ButtonOpenFiles" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but50 <ButtonRelease-1> {
        lambda e: openFilesButton(e)
    }
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Remove 
    vTcl:DefineAlias "$site_3_0.but51" "ButtonRemoveCurrent" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but51 <ButtonRelease-1> {
        lambda e: removeCurrentSampleButton(e)
    }
    button $site_3_0.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Reload All} 
    vTcl:DefineAlias "$site_3_0.but61" "ButtonReloadAllSamples" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but61 <Button-1> {
        lambda e: reloadAllSamplesButton(e)
    }
    button $site_3_0.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Change Path} 
    vTcl:DefineAlias "$site_3_0.but62" "ButtonChangeSamplePathOfCurrent" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but62 <ButtonRelease-1> {
        lambda e: changePathOfCurrentSampleButton(e)
    }
    place $site_3_0.lis47 \
        -in $site_3_0 -x 10 -y 20 -width 508 -relwidth 0 -height 227 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.82 -y 0 -rely 0.061 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 540 -y 200 -width 87 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 538 -y 65 -width 87 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 540 -y 160 -width 87 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f0f0f0f0f0f0 \
        -highlightcolor black -highlightthickness 1 -relief groove \
        -text {Source Samples} 
    vTcl:DefineAlias "$top.lab49" "LabelSourceSamples" vTcl:WidgetProc "Toplevel" 1
    frame $top.fra55 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 253 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 490 
    vTcl:DefineAlias "$top.fra55" "FrameLoopSettings" vTcl:WidgetProc "Toplevel" 1
    set site_3_0 $top.fra55
    button $site_3_0.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Import Project} 
    vTcl:DefineAlias "$site_3_0.but60" "ButtonImportProject" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but60 <ButtonRelease-1> {
        lambda e: importProjectButton(e)
    }
    button $site_3_0.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Export Project} 
    vTcl:DefineAlias "$site_3_0.but64" "ButtonExportProject" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but64 <ButtonRelease-1> {
        lambda e: exportProjectButton(e)
    }
    spinbox $site_3_0.spi65 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_loop_settings -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxFireCount -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi65" "SpinboxFireCount" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi65 <KeyRelease> {
        lambda e: on_loop_settings_changed(e)
    }
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Fire Count} 
    vTcl:DefineAlias "$site_3_0.lab66" "LabelFireCount" vTcl:WidgetProc "Toplevel" 1
    button $site_3_0.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Set Target Directory} 
    vTcl:DefineAlias "$site_3_0.but67" "ButtonSetTargetDirectory" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but67 <ButtonRelease-1> {
        lambda e: setTargetDirectoryButton(e)
    }
    checkbutton $site_3_0.che68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor nw -background $vTcl(actual_gui_bg) \
        -command update_loop_settings -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable checkNormalize 
    vTcl:DefineAlias "$site_3_0.che68" "CheckNormalizeLoop" vTcl:WidgetProc "Toplevel" 1
    spinbox $site_3_0.spi73 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_loop_settings -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxSeed -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi73" "SpinboxSeed" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi73 <KeyRelease> {
        lambda e: on_loop_settings_changed(e)
    }
    label $site_3_0.lab74 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Seed 
    vTcl:DefineAlias "$site_3_0.lab74" "LabelSeed" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab75 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Normalize 
    vTcl:DefineAlias "$site_3_0.lab75" "LabelNormalize" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab76 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Please Set Target Path} -textvariable labelTargetDirectory 
    vTcl:DefineAlias "$site_3_0.lab76" "LabelTargetPatch" vTcl:WidgetProc "Toplevel" 1
    spinbox $site_3_0.spi79 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_loop_settings -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxRPM -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi79" "SpinboxRPM" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi79 <KeyRelease> {
        lambda e: on_loop_settings_changed(e)
    }
    label $site_3_0.lab80 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text RPM 
    vTcl:DefineAlias "$site_3_0.lab80" "LabelRPM" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {RPM Burst} 
    vTcl:DefineAlias "$site_3_0.lab81" "LabelRPMBurst" vTcl:WidgetProc "Toplevel" 1
    spinbox $site_3_0.spi82 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_loop_settings -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxRPMBurst -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi82" "SpinboxRPMBurst" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi82 <KeyRelease> {
        lambda e: on_loop_settings_changed(e)
    }
    label $site_3_0.lab83 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Burst Count} 
    vTcl:DefineAlias "$site_3_0.lab83" "LabelBurstCount" vTcl:WidgetProc "Toplevel" 1
    spinbox $site_3_0.spi84 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_loop_settings -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxBurstCount -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi84" "SpinboxBurstCount" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi84 <KeyRelease> {
        lambda e: on_loop_settings_changed(e)
    }
    label $site_3_0.lab85 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Prefix 
    vTcl:DefineAlias "$site_3_0.lab85" "LabelPrefix" vTcl:WidgetProc "Toplevel" 1
    entry $site_3_0.ent122 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable textPrefix -width 214 
    vTcl:DefineAlias "$site_3_0.ent122" "EntryPrefix" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.ent122 <ButtonRelease-1> {
        lambda e: on_loop_settings_changed(e)
    }
    bind $site_3_0.ent122 <KeyRelease> {
        lambda e: on_loop_settings_changed(e)
    }
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Mono Loop} 
    vTcl:DefineAlias "$site_3_0.lab45" "LabelMonoLoop" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Mono Tail} 
    vTcl:DefineAlias "$site_3_0.lab46" "LabelMonoTail" vTcl:WidgetProc "Toplevel" 1
    checkbutton $site_3_0.che47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor nw -background $vTcl(actual_gui_bg) \
        -command update_loop_settings -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable checkMonoLoop 
    vTcl:DefineAlias "$site_3_0.che47" "CheckbuttonMonoLoop" vTcl:WidgetProc "Toplevel" 1
    checkbutton $site_3_0.che48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command update_loop_settings \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable checkMonoTail 
    vTcl:DefineAlias "$site_3_0.che48" "CheckbuttonMonoTail" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Variations 
    vTcl:DefineAlias "$site_3_0.lab47" "LabelVariations" vTcl:WidgetProc "Toplevel" 1
    spinbox $site_3_0.spi48 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -command update_loop_settings -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable spinboxVariations -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi48" "SpinboxVariations" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.spi48 <KeyRelease> {
        lambda e: on_loop_settings_changed(e)
    }
    place $site_3_0.but60 \
        -in $site_3_0 -x 8 -y 21 -width 117 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 8 -y 74 -width 117 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi65 \
        -in $site_3_0 -x 240 -y 21 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 140 -y 21 -width 62 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 0 -relx 0.02 -y 0 -rely 0.83 -width 117 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che68 \
        -in $site_3_0 -x 235 -y 85 -width 48 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi73 \
        -in $site_3_0 -x 419 -y 85 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 329 -y 85 -width 37 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 140 -y 85 -width 89 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 130 -y 220 -width 338 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi79 \
        -in $site_3_0 -x 419 -y 21 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab80 \
        -in $site_3_0 -x 329 -y 21 -width 28 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 329 -y 53 -width 61 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi82 \
        -in $site_3_0 -x 0 -relx 0.853 -y 0 -rely 0.209 -width 0 \
        -relwidth 0.077 -height 0 -relheight 0.079 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 140 -y 53 -width 82 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi84 \
        -in $site_3_0 -x 240 -y 50 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 140 -y 180 -width 37 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent122 \
        -in $site_3_0 -x 240 -y 180 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 140 -y 120 -width 68 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 330 -y 120 -width 59 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che47 \
        -in $site_3_0 -x 235 -y 120 -width 28 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che48 \
        -in $site_3_0 -x 415 -y 120 -width 28 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 140 -y 150 -width 74 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi48 \
        -in $site_3_0 -x 240 -y 150 -width 35 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text {Loop Settings} 
    vTcl:DefineAlias "$top.lab56" "LabelLoopSettings" vTcl:WidgetProc "Toplevel" 1
    frame $top.fra69 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 253 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 282 
    vTcl:DefineAlias "$top.fra69" "FramePreview" vTcl:WidgetProc "Toplevel" 1
    set site_3_0 $top.fra69
    button $site_3_0.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Play 
    vTcl:DefineAlias "$site_3_0.but71" "ButtonPlayPreview" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but71 <Button-1> {
        lambda e: playPreviewButton(e)
    }
    button $site_3_0.but72 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Regenerate Loop} 
    vTcl:DefineAlias "$site_3_0.but72" "ButtonRegenerateLoop" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but72 <Button-1> {
        lambda e: regeneratePreviewLoopButton(e)
    }
    button $site_3_0.but88 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Regenerate Burst} 
    vTcl:DefineAlias "$site_3_0.but88" "ButtonRegenerateBurst" vTcl:WidgetProc "Toplevel" 1
    bind $site_3_0.but88 <Button-1> {
        lambda e: regeneratePreviewBurstButton(e)
    }
    label $site_3_0.lab89 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {max dBFS} 
    vTcl:DefineAlias "$site_3_0.lab89" "LabelMaxPreview" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab90 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text dBFS 
    vTcl:DefineAlias "$site_3_0.lab90" "LabelAVGPreview" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab91 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text -12 -textvariable maxVolumePreview 
    vTcl:DefineAlias "$site_3_0.lab91" "MaxVolumePreview" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab92 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text -12 -textvariable avgVolumePreview 
    vTcl:DefineAlias "$site_3_0.lab92" "AVGVolumePreview" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab93 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Volume 
    vTcl:DefineAlias "$site_3_0.lab93" "LabelVolumePreview" vTcl:WidgetProc "Toplevel" 1
    place $site_3_0.but71 \
        -in $site_3_0 -x 10 -y 180 -width 130 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but72 \
        -in $site_3_0 -x 10 -y 20 -width 130 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but88 \
        -in $site_3_0 -x 10 -y 70 -width 130 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab89 \
        -in $site_3_0 -x 160 -y 50 -width 58 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 160 -y 70 -width 47 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab91 \
        -in $site_3_0 -x 230 -y 50 -width 43 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab92 \
        -in $site_3_0 -x 230 -y 70 -width 40 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab93 \
        -in $site_3_0 -x 160 -y 30 -width 48 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab70 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Preview 
    vTcl:DefineAlias "$top.lab70" "LabelPreview" vTcl:WidgetProc "Toplevel" 1
    button $top.but97 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Generate Game Files} 
    vTcl:DefineAlias "$top.but97" "ButtonGenerateGameFiles" vTcl:WidgetProc "Toplevel" 1
    bind $top.but97 <Button-1> {
        lambda e: generateGameFilesButton(e)
    }
    label $top.lab98 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text {Sample Properties} 
    vTcl:DefineAlias "$top.lab98" "LabelSampleProperties" vTcl:WidgetProc "Toplevel" 1
    label $top.lab47 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Ready \
        -textvariable labelAppLog 
    vTcl:DefineAlias "$top.lab47" "LabelAppLog" vTcl:WidgetProc "Toplevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -relx 0.599 -y 0 -rely 0.051 -width 0 -relwidth 0.386 \
        -height 0 -relheight 0.444 -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.051 -width 0 -relwidth 0.554 \
        -height 0 -relheight 0.444 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.008 -y 0 -rely 0.022 -width 0 -relwidth 0.11 \
        -height 0 -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.fra55 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.541 -width 0 -relwidth 0.414 \
        -height 0 -relheight 0.427 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.008 -y 0 -rely 0.507 -width 0 -relwidth 0.116 \
        -height 0 -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.fra69 \
        -in $top -x 0 -relx 0.456 -y 0 -rely 0.541 -width 0 -relwidth 0.238 \
        -height 0 -relheight 0.427 -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 0 -relx 0.448 -y 0 -rely 0.507 -width 0 -relwidth 0.086 \
        -height 0 -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.but97 \
        -in $top -x 0 -relx 0.768 -y 0 -rely 0.659 -width 177 -relwidth 0 \
        -height 104 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab98 \
        -in $top -x 0 -relx 0.591 -y 0 -rely 0.017 -width 0 -relwidth 0.128 \
        -height 0 -relheight 0.052 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.895 -width 0 -relwidth 0.284 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

